### ISSUE TITLE
4.0.0 Can't find module (Electron App)

### ISSUE THREAD

**Issue by Gurrman375** [XboxReplay/xboxlive-auth#17]
I attempted to build and run the electron app but got this error. I can start it in electron but can't seem to build it.
```
C:\Users\<user>\Documents\xboxlive-auth\examples\electron-app>npm start build

> @xboxreplay/xboxlive-auth_electron-app@0.0.1 start
> electron . "build"


App threw an error during load
Error: Cannot find module 'C:\Users\<user>\Documents\xboxlive-auth\examples\electron-app\node_modules\@xboxreplay\xboxlive-auth\dist\index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:328:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:689:18)
    at Module._resolveFilename (internal/modules/cjs/loader.js:959:27)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:249:921)
    at Module._load (internal/modules/cjs/loader.js:848:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\<user>\Documents\xboxlive-auth\examples\electron-app\lib\main.js:2:23)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
```

**Comment by Alexis-Bize** [comment]
Hey @Gurrman375, thanks for the report! A fix has been pushed to the repository 👍
Please make sure to delete generated `node_modules` directories.

**Comment by Gurrman375** [comment]
I deleted the `node_modules` from the folder and updated the code you push and reran the code and it gave me this issue:
```
C:\Users\<user>\Documents\xboxlive-auth\examples\electron-app>npm install

> @xboxreplay/xboxlive-auth_electron-app@0.0.1 preinstall
> npm install --prefix ../../ && npm run build

npm ERR! code 1
npm ERR! path C:\Users\<user>\Documents\xboxlive-auth\examples\electron-app
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c npm install --prefix ../../ && npm run build
npm ERR! removed 88 packages, and audited 76 packages in 1s
npm ERR!
npm ERR! 1 package is looking for funding
npm ERR!   run `npm fund` for details
npm ERR!
npm ERR! found 0 vulnerabilities
npm ERR!
npm ERR! > @xboxreplay/xboxlive-auth_electron-app@0.0.1 build
npm ERR! > npm run build --prefix ../../
npm ERR!
npm ERR!
npm ERR! > @xboxreplay/xboxlive-auth@4.0.0-beta.5 build
npm ERR! > npm run clean && ./node_modules/.bin/tsc
npm ERR!
npm ERR!
npm ERR! > @xboxreplay/xboxlive-auth@4.0.0-beta.5 clean
npm ERR! > rm -rf ./dist
npm ERR! 'rm' is not recognized as an internal or external command,
npm ERR! operable program or batch file.
npm ERR! npm ERR! code 1
npm ERR! npm ERR! path C:\Users\<user>\Documents\xboxlive-auth
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command C:\Windows\system32\cmd.exe /d /s /c rm -rf ./dist
npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     C:\Users\<user>\AppData\Local\npm-cache\_logs\2021-05-12T19_53_24_236Z-debug.log
npm ERR! npm ERR! code 1
npm ERR! npm ERR! path C:\Users\<user>\Documents\xboxlive-auth
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command C:\Windows\system32\cmd.exe /d /s /c npm run clean && ./node_modules/.bin/tsc
npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     C:\Users\<user>\AppData\Local\npm-cache\_logs\2021-05-12T19_53_24_254Z-debug.log
npm ERR! npm ERR! code 1
npm ERR! npm ERR! path C:\Users\<user>\Documents\xboxlive-auth\examples\electron-app
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command C:\Windows\system32\cmd.exe /d /s /c npm run build --prefix ../../
npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     C:\Users\<user>\AppData\Local\npm-cache\_logs\2021-05-12T19_53_24_273Z-debug.log

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\<user>\AppData\Local\npm-cache\_logs\2021-05-12T19_53_24_462Z-debug.log
npm ERR! code 1
npm ERR! path C:\Users\<user>\Documents\xboxlive-auth\examples\electron-app
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c npm install --prefix ../../ && npm run build

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\<user>\AppData\Local\npm-cache\_logs\2021-05-12T19_53_24_492Z-debug.log
```

**Comment by Alexis-Bize** [comment]
@Gurrman375 Oh I noticed you're using Windows, as used `rm -rf` command is not supported I've updated `package.json` file to use `rimraf` module instead. It should be OK now :)

**Comment by Gurrman375** [comment]
Looks like `npm install` is working now. `npm start` is missing and when I try to build `npm run build` I either get:
```
'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code 1
npm ERR! path C:\Users\<user>\Documents\xboxlive-auth\examples\electron-app
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c npm run clean && ./node_modules/.bin/tsc

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\<user>\AppData\Local\npm-cache\_logs\2021-05-12T21_13_07_040Z-debug.log
```
or:
```
> @xboxreplay/xboxlive-auth@4.0.0-beta.5 clean
> rimraf ./dist

The system cannot find the path specified.
npm ERR! code 1
npm ERR! path C:\Users\<user>\Documents\xboxlive-auth\examples\electron-app
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c npm run clean && /node_modules/.bin/tsc

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\<user>\AppData\Local\npm-cache\_logs\2021-05-12T21_15_19_511Z-debug.log
```

**Comment by Gurrman375** [comment]
Now I have to look through all these errors:
```
../../src/classes/XRError.ts:132:20 - error TS2339: Property 'captureStackTrace' does not exist on type 'ErrorConstructor'.

132   if (typeof Error.captureStackTrace === 'function')
                       ~~~~~~~~~~~~~~~~~

../../src/classes/XRError.ts:133:10 - error TS2339: Property 'captureStackTrace' does not exist on type 'ErrorConstructor'.

133    Error.captureStackTrace(this, this.constructor);
             ~~~~~~~~~~~~~~~~~

../../src/core/live/index.ts:1:35 - error TS2307: Cannot find module 'axios' or its corresponding type declarations.

1 import axios, { AxiosError } from 'axios';
                                    ~~~~~~~

../../src/core/live/index.ts:2:27 - error TS2307: Cannot find module 'querystring' or its corresponding type declarations.

2 import { stringify } from 'querystring';
                            ~~~~~~~~~~~~~

../../src/core/live/index.ts:101:9 - error TS7006: Parameter 'res' implicitly has an 'any' type.

101   .then(res => res.data)
            ~~~

../../src/core/live/index.ts:155:9 - error TS7006: Parameter 'res' implicitly has an 'any' type.

155   .then(res => res.data)
            ~~~

../../src/core/live/index.ts:189:9 - error TS7006: Parameter 'res' implicitly has an 'any' type.

189   .then(res => {
            ~~~

../../src/core/live/index.ts:211:10 - error TS7006: Parameter 'err' implicitly has an 'any' type.

211   .catch(err => {
             ~~~

../../src/core/live/index.ts:245:19 - error TS7006: Parameter 'status' implicitly has an 'any' type.

245   validateStatus: status => status === 302 || status === 200
                      ~~~~~~

../../src/core/live/index.ts:247:9 - error TS7006: Parameter 'res' implicitly has an 'any' type.

247   .then(res => {
            ~~~

../../src/core/live/index.ts:266:10 - error TS7006: Parameter 'err' implicitly has an 'any' type.

266   .catch(err => {
             ~~~

../../src/core/xboxlive/index.ts:1:35 - error TS2307: Cannot find module 'axios' or its corresponding type declarations.

1 import axios, { AxiosError } from 'axios';
                                    ~~~~~~~

../../src/core/xboxlive/index.ts:67:9 - error TS7006: Parameter 'res' implicitly has an 'any' type.

67   .then(res => res.data)
           ~~~

../../src/core/xboxlive/index.ts:68:10 - error TS7006: Parameter '_' implicitly has an 'any' type.

68   .catch(_ => {
            ~

../../src/core/xboxlive/index.ts:126:9 - error TS7006: Parameter 'res' implicitly has an 'any' type.

126   .then(res => res.data)
            ~~~

../../src/core/xboxlive/index.ts:210:9 - error TS7006: Parameter 'res' implicitly has an 'any' type.

210   .then(res => res.data)
            ~~~

../../src/core/xboxlive/index.ts:211:10 - error TS7006: Parameter '_' implicitly has an 'any' type.

211   .catch(_ => {
```

**Comment by Gurrman375** [comment]
All I had to do for this was restart my ide. Thanks for the help.

**Comment by Alexis-Bize** [comment]
@Gurrman375 Haha, yeah sorry I didn't had time today to look further but glad it worked! :)
