### ISSUE TITLE
A problem

### ISSUE THREAD

**Issue by whes1015** [XboxReplay/xboxlive-auth#19]
C:\Users\whes1015\Desktop\discordbot>node index.js
(node:7464) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\whes1015\Desktop\discordbot\index.js:9
import XboxLiveAuth from '@xboxreplay/xboxlive-auth';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

**Comment by Alexis-Bize** [comment]
Hey @whes1015,
There's few reasons / workarounds regarding your issue.

- Outdated Node.js version (<= 12)
- Missing `"type": "module"` in your `package.json`
- ES6 import not supported (related to your Node.js version or missing transpiler such as Babel)

Try to require the module instead of importing it.
```
const XboxLiveAuth = require('@xboxreplay/xboxlive-auth');
```

**Comment by Alexis-Bize** [comment]
No activity :) Closing
